# -*- coding: utf-8 -*-
"""exp-4a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drUi1u8i2utjSgiHDlwLZvchDZ6r_guV

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
"""

!pip install -q git+https://github.com/feralvam/easse.git
!pip install -q transformers peft bitsandbytes accelerate datasets \
    sentencepiece protobuf bert-score textstat scispacy
!pip install -q https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_lg-0.5.4.tar.gz

!pip freeze | grep -E "transformers|peft|bitsandbytes|accelerate|datasets|bert.score|textstat|torch"

import os; os.kill(os.getpid(), 9)

import os, json, gc, time, warnings, torch, numpy as np, spacy, textstat
from datasets import load_from_disk
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from bert_score import BERTScorer
from easse.sari import corpus_sari
from datetime import datetime
from google.colab import drive
from huggingface_hub import login

warnings.filterwarnings("ignore", message=".*`do_sample` is set to `False`.*")
drive.mount("/content/drive")

SEED = 42

HF_TOKEN = "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"
login(token=HF_TOKEN)

ROOT        = "/content/drive/MyDrive/Gatekeepn't/Data/processed"
RESULTS_DIR = "/content/drive/MyDrive/Gatekeepn't/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

test_sells    = load_from_disk(f"{ROOT}/test_sells")
test_medlane  = load_from_disk(f"{ROOT}/test_medlane")
test_cochrane = load_from_disk(f"{ROOT}/test_cochrane")
test_plaba    = load_from_disk(f"{ROOT}/test_plaba")

ent_nlp = spacy.load("en_core_sci_lg")

PREFIXES = {
    "sells":    "[BIOMED]",
    "medlane":  "[CLINICAL]",
    "cochrane": "[REVIEW]",
    "plaba":    "[BIOMED]",
}

SAVE_EVERY_N_BATCHES = 5


def predict_batched(ds, batch_size, save_path=None):
    preds = []
    if save_path and os.path.exists(save_path):
        with open(save_path) as f:
            preds = json.load(f)
        print(f"  resuming from {len(preds)}/{len(ds)}")

    start = len(preds)
    total = len(ds)

    if start >= total:
        print(f"  already complete ({total}/{total})")
        return preds

    empty_count = 0
    t0 = time.time()

    for i in range(start, total, batch_size):
        end   = min(i + batch_size, total)
        batch = ds[i:end]

        prompts = []
        for src, d in zip(batch["source"], batch["dataset"]):
            prompts.append(
                f"{PREFIXES[d]} Simplify the following medical text into plain "
                f"language that a patient without medical training can "
                f"understand:\n\n{src}"
            )

        # For seq2seq: padding_side stays right (encoder processes full sequence)
        # max_length here caps the encoder input, not the decoder output
        encoded = tok(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=1024,
        ).to(model.device)

        with torch.no_grad():
            out = model.generate(
                **encoded,
                max_new_tokens=1024,
                do_sample=False,
                repetition_penalty=1.1,
                pad_token_id=tok.pad_token_id,
            )

        # seq2seq generate() returns decoder-only tokens — no input_len slicing
        for j in range(out.shape[0]):
            text = tok.decode(out[j], skip_special_tokens=True).strip()
            if not text:
                text = "[EMPTY]"
                empty_count += 1
            preds.append(text)

        batch_num = (i - start) // batch_size + 1
        elapsed   = time.time() - t0
        rate      = (end - start) / elapsed if elapsed > 0 else 0
        eta       = (total - end) / rate if rate > 0 else 0
        warn      = f"  [EMPTY: {empty_count}]" if empty_count else ""
        print(f"  {end:>6}/{total}  |  {rate:.1f} ex/s  |  ETA {eta / 60:.0f}m{warn}")

        if batch_num % SAVE_EVERY_N_BATCHES == 0 or end == total:
            if save_path:
                with open(save_path, "w") as f:
                    json.dump(preds, f)

    if empty_count:
        print(f"  WARNING: {empty_count}/{total} empty predictions")
    return preds


def per_example_sari(srcs, preds, refs):
    return [corpus_sari([s], [p], [[r]]) for s, p, r in zip(srcs, preds, refs)]


def per_example_entity(srcs, preds):
    src_ents  = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(srcs, batch_size=512)]
    pred_ents = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(preds, batch_size=512)]
    ps, rs, f1s = [], [], []
    for s_set, p_set in zip(src_ents, pred_ents):
        overlap = len(p_set & s_set)
        if len(p_set) == 0 and len(s_set) == 0:
            p, r = 1.0, 1.0
        elif len(p_set) == 0:
            p, r = 0.0, 0.0
        elif len(s_set) == 0:
            p, r = 0.0, 1.0
        else:
            p = overlap / len(p_set)
            r = overlap / len(s_set)
        f = (2 * p * r / (p + r)) if (p + r) > 0 else 0.0
        ps.append(p); rs.append(r); f1s.append(f)
    return ps, rs, f1s


def per_example_readability(srcs, preds):
    fre_d, fkg_d, valid_idx = [], [], []
    for i, (src, pred) in enumerate(zip(srcs, preds)):
        s, p = src.strip(), pred.strip()
        if s and p and p != "[EMPTY]":
            fre_d.append(textstat.flesch_reading_ease(p)
                         - textstat.flesch_reading_ease(s))
            fkg_d.append(textstat.flesch_kincaid_grade(p)
                         - textstat.flesch_kincaid_grade(s))
            valid_idx.append(i)
    return fre_d, fkg_d, valid_idx


def bootstrap_mean_ci(scores, n_boot=1000, ci=95):
    arr = np.array(scores)
    rng = np.random.RandomState(SEED)
    n   = len(arr)
    means = [arr[rng.randint(0, n, size=n)].mean() for _ in range(n_boot)]
    lo = np.percentile(means, (100 - ci) / 2)
    hi = np.percentile(means, 100 - (100 - ci) / 2)
    return round(float(lo), 4), round(float(hi), 4)


def evaluate(tag, ds, preds, scorer):
    srcs = list(ds["source"])
    refs = list(ds["target"])
    n    = len(ds)

    print(f"\n{'─' * 55}")
    print(f"  {tag.upper()} ({n} examples)")
    print(f"{'─' * 55}")

    print("  SARI (per-sentence) ...")
    sari_scores = per_example_sari(srcs, preds, refs)

    print("  BERTScore ...")
    _, _, bs_f1 = scorer.score(preds, refs)
    bert_scores = bs_f1.tolist()

    print("  Entity P/R/F1 ...")
    ep_scores, er_scores, ef1_scores = per_example_entity(srcs, preds)

    print("  Readability ...")
    fre_d, fkg_d, read_idx = per_example_readability(srcs, preds)

    result = dict(
        n       = n,
        sari    = round(float(np.mean(sari_scores)), 2),
        bert_f1 = round(float(np.mean(bert_scores)), 4),
        ent_p   = round(float(np.mean(ep_scores)), 4),
        ent_r   = round(float(np.mean(er_scores)), 4),
        ent_f1  = round(float(np.mean(ef1_scores)), 4),
        d_fre   = round(float(np.mean(fre_d)), 2),
        d_fkg   = round(float(np.mean(fkg_d)), 2),
        n_empty = sum(1 for p in preds if p == "[EMPTY]"),
        n_read  = len(read_idx),
    )

    print("  Bootstrap CIs (1000 resamples) ...")
    result["sari_ci"]    = bootstrap_mean_ci(sari_scores)
    result["bert_f1_ci"] = bootstrap_mean_ci(bert_scores)
    result["ent_f1_ci"]  = bootstrap_mean_ci(ef1_scores)
    result["d_fre_ci"]   = bootstrap_mean_ci(fre_d)

    print(f"  SARI  = {result['sari']:.2f}  {result['sari_ci']}")
    print(f"  BS    = {result['bert_f1']:.4f}  {result['bert_f1_ci']}")
    print(f"  EntP  = {result['ent_p']:.4f}  |  EntR = {result['ent_r']:.4f}  "
          f"|  EntF1 = {result['ent_f1']:.4f}  {result['ent_f1_ci']}")
    print(f"  dFRE  = {result['d_fre']:+.2f}  {result['d_fre_ci']}  |  "
          f"dFKG = {result['d_fkg']:+.2f}")
    if result["n_empty"]:
        print(f"  ⚠ {result['n_empty']} empty predictions")

    per_ex = dict(
        sari=sari_scores, bert_f1=bert_scores,
        ent_p=ep_scores, ent_r=er_scores, ent_f1=ef1_scores,
    )
    return result, per_ex


def print_summary(results, tags):
    print(f"\n{'dataset':<11} {'SARI':>6} {'95% CI':>14} {'BS':>7} "
          f"{'EntP':>6} {'EntR':>6} {'EntF1':>6} {'95% CI':>14} "
          f"{'dFRE':>6} {'dFKG':>6}")
    print("─" * 105)
    for tag in tags:
        r = results[tag]
        sci = f"[{r['sari_ci'][0]:.2f},{r['sari_ci'][1]:.2f}]"
        eci = f"[{r['ent_f1_ci'][0]:.4f},{r['ent_f1_ci'][1]:.4f}]"
        print(f"{tag:<11} {r['sari']:>6.2f} {sci:>14} {r['bert_f1']:>7.4f} "
              f"{r['ent_p']:>6.4f} {r['ent_r']:>6.4f} {r['ent_f1']:>6.4f} "
              f"{eci:>14} {r['d_fre']:>+6.2f} {r['d_fkg']:>+6.2f}")

print(f"sells={len(test_sells)}, medlane={len(test_medlane)}, "
      f"cochrane={len(test_cochrane)}, plaba={len(test_plaba)}")

MODEL_ID = "GanjinZero/biobart-v2-large"

tok = AutoTokenizer.from_pretrained(MODEL_ID)
# Do NOT override pad_token — BioBART (BART-based) has its own <pad> token (id=1)
# Overriding with eos_token like the Llama notebooks would break decoder generation

model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=True,
)
model.eval()

gpu_name = torch.cuda.get_device_name(0)
vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"GPU : {gpu_name} ({vram_gb:.0f} GB)")
print(f"VRAM: {torch.cuda.memory_allocated() / 1e9:.2f} GB used by model")

if vram_gb >= 70:
    BATCH_SHORT = 128
    BATCH_LONG  = 64
elif vram_gb >= 40:
    BATCH_SHORT = 32
    BATCH_LONG  = 16
else:
    BATCH_SHORT = 8
    BATCH_LONG  = 4

print(f"batch sizes: short={BATCH_SHORT}, long={BATCH_LONG}")

all_preds = {}

for tag, ds, bs in [
    ("sells",    test_sells,    BATCH_SHORT),
    ("medlane",  test_medlane,  BATCH_SHORT),
    ("cochrane", test_cochrane, BATCH_LONG),
    ("plaba",    test_plaba,    BATCH_SHORT),
]:
    save_path = f"{RESULTS_DIR}/exp4a_preds_{tag}.json"
    print(f"\n{'=' * 55}")
    print(f"  {tag.upper()} — {len(ds)} examples, batch={bs}")
    print(f"{'=' * 55}")
    all_preds[tag] = predict_batched(ds, batch_size=bs, save_path=save_path)

print(f"\nall predictions complete.")

scorer = BERTScorer(
    model_type="allenai/scibert_scivocab_uncased",
    batch_size=128,
    device="cuda:0",
)
scorer._tokenizer.model_max_length = 512

# reload from drive if kernel restarted
for tag in ["sells", "medlane", "cochrane", "plaba"]:
    if tag not in all_preds:
        path = f"{RESULTS_DIR}/exp4a_preds_{tag}.json"
        with open(path) as f:
            all_preds[tag] = json.load(f)
        print(f"  loaded {tag} from drive")

results     = {}
per_example = {}

print("=" * 60)
print("  TIER 1 — IN-DOMAIN")
print("=" * 60)

for tag, ds in [("sells", test_sells), ("medlane", test_medlane),
                ("cochrane", test_cochrane)]:
    results[tag], per_example[tag] = evaluate(tag, ds, all_preds[tag], scorer)

print("\n" + "=" * 60)
print("  TIER 2 — OUT-OF-DISTRIBUTION BIOMEDICAL")
print("=" * 60)

results["plaba"], per_example["plaba"] = evaluate(
    "plaba", test_plaba, all_preds["plaba"], scorer)

print_summary(results, ["sells", "medlane", "cochrane", "plaba"])

print("\nSARI verification (per-sentence mean vs corpus-level):")
for tag in ["sells", "medlane", "cochrane", "plaba"]:
    ds_ref = {"sells": test_sells, "medlane": test_medlane,
              "cochrane": test_cochrane, "plaba": test_plaba}[tag]
    corpus = corpus_sari(list(ds_ref["source"]), all_preds[tag], [list(ds_ref["target"])])
    print(f"  {tag}: per-sentence={results[tag]['sari']:.2f}, corpus={corpus:.2f}")

output = {
    "experiment":  "exp4a_zero_shot_biobart",
    "timestamp":   datetime.now().isoformat(),
    "description": (
        "Zero-shot BioBART-v2-large (GanjinZero/biobart-v2-large), bf16, "
        "no fine-tuning, batched greedy decoding, full test sets, "
        "bootstrap 95% CIs (n=1000, seed=42)"
    ),
    "model":    MODEL_ID,
    "gpu":      torch.cuda.get_device_name(0),
    "vram_gb":  round(vram_gb, 1),
    "precision": "bf16",
    "architecture": "encoder-decoder (seq2seq)",
    "seed": SEED,
    "generation_config": {
        "max_new_tokens":     1024,
        "encoder_max_length": 1024,
        "do_sample":          False,
        "repetition_penalty": 1.1,
        "batch_short":        BATCH_SHORT,
        "batch_long":         BATCH_LONG,
    },
    "test_sizes": {
        t: len(d) for t, d in [("sells", test_sells), ("medlane", test_medlane),
                                ("cochrane", test_cochrane), ("plaba", test_plaba)]
    },
    "library_versions": {
        "transformers": __import__("transformers").__version__,
        "torch":        torch.__version__,
        "datasets":     __import__("datasets").__version__,
        "bert_score":   __import__("bert_score").__version__,
    },
    "results": results,
}

path = f"{RESULTS_DIR}/exp4a_zero_shot_biobart.json"
with open(path, "w") as f:
    json.dump(output, f, indent=2)
print(f"saved results     → {path}")

path_pe = f"{RESULTS_DIR}/exp4a_per_example.json"
with open(path_pe, "w") as f:
    json.dump(per_example, f)
print(f"saved per-example → {path_pe}")

print("\n" + "=" * 60)
print("  FINAL RESULTS — EXP 4a ZERO-SHOT BIOBART")
print("=" * 60)
print_summary(results, ["sells", "medlane", "cochrane", "plaba"])