# -*- coding: utf-8 -*-
"""Exp_3a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAne5SHKtiKmgtRiymeWo49MsPjpYLau
"""

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

from google.colab import drive
drive.mount('/content/drive')

!pip install -q git+https://github.com/feralvam/easse.git
!pip install -q transformers peft bitsandbytes accelerate datasets \
    sentencepiece protobuf bert-score textstat scispacy trl
!pip install -q https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_lg-0.5.4.tar.gz

!pip freeze | grep -E "transformers|peft|bitsandbytes|accelerate|datasets|bert.score|textstat|torch|trl"

# Removed: import os; os.kill(os.getpid(), 9)

import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import AutoPeftModelForCausalLM
import torch

# Re-initialize token for HuggingFace Hub login if needed after kernel restart
if 'HF_TOKEN' not in locals():
    HF_TOKEN = "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"
    from huggingface_hub import login
    login(token=HF_TOKEN)

# Define paths (if not already defined, e.g., after kernel restart)
if 'OUTPUT_DIR' not in locals():
    OUTPUT_DIR = "/content/drive/MyDrive/Gatekeepn't/models/exp3a_mixed_1024"
    RESULTS_DIR = "/content/drive/MyDrive/Gatekeepn't/results"

# --- Load best model and tokenizer for inference ---
# The training cell (4B8oTJ4haHk7) saves the best checkpoint and tokenizer
# and then merges the LoRA adapter into the base model.
# We will directly load the 'best' checkpoint saved by the Trainer.

# If the merged_bf16 model exists, load that. Otherwise, load from 'best' and merge.
merged_path = f"{OUTPUT_DIR}/merged_bf16"

if os.path.exists(merged_path):
    print(f"Loading merged bf16 model from {merged_path}...")
    model = AutoModelForCausalLM.from_pretrained(
        merged_path,
        dtype=torch.bfloat16,
        device_map="auto",
        low_cpu_mem_usage=True,
        attn_implementation="sdpa",
    )
    tok = AutoTokenizer.from_pretrained(merged_path, token=HF_TOKEN)
else:
    print(f"Merged model not found at {merged_path}. Loading from best checkpoint and merging...")
    # First, load the PEFT model from the best checkpoint
    peft_model = AutoPeftModelForCausalLM.from_pretrained(
        f"{OUTPUT_DIR}/best",
        dtype=torch.bfloat16, # Or whatever dtype was used during training/inference setup
        low_cpu_mem_usage=True,
        device_map="auto",
        token=HF_TOKEN,
    )
    # Merge and unload to get the full model
    model = peft_model.merge_and_unload()
    model.save_pretrained(merged_path) # Save merged model for future use
    tok = AutoTokenizer.from_pretrained(f"{OUTPUT_DIR}/best", token=HF_TOKEN)
    tok.save_pretrained(merged_path)

model.eval()
tok.pad_token = tok.eos_token
tok.padding_side = "right"

# --- Re-initialize variables from training ---
# These were previously set by the trainer.train() call.
# Assuming the training history was saved.
import json
history_path = f"{RESULTS_DIR}/exp3a_train_history.json"

if os.path.exists(history_path):
    with open(history_path, "r") as f:
        log_history = json.load(f)
    # Find the last 'save_steps' or 'eval_loss' entry to get the best checkpoint info
    best_checkpoint_info = None
    best_eval_loss_val = float('inf')
    current_step = 0

    for entry in log_history:
        if 'eval_loss' in entry and entry['eval_loss'] < best_eval_loss_val:
            best_eval_loss_val = entry['eval_loss']
            # Assuming checkpoint steps are consistent with log entries
            # This is a heuristic, exact checkpoint name might need more robust logic
            current_step = entry.get('step', current_step) # Use step from log if available
            # Try to infer checkpoint path from step, or look for specific checkpoint keys
            best_checkpoint_info = f"{OUTPUT_DIR}/checkpoint-{current_step}"
        if 'step' in entry:
            current_step = entry['step']

    if best_checkpoint_info:
        best_checkpoint = best_checkpoint_info
        best_eval_loss = round(best_eval_loss_val, 4)
        total_steps = current_step # Last recorded step
        print(f"Re-initialized best_checkpoint: {best_checkpoint}")
        print(f"Re-initialized best_eval_loss: {best_eval_loss}")
        print(f"Re-initialized total_steps: {total_steps}")
    else:
        print("Could not infer best checkpoint info from history. Setting defaults.")
        best_checkpoint = f"{OUTPUT_DIR}/best"
        best_eval_loss = 1.9990 # Default value from previous output
        total_steps = 5000 # Default value from previous output
else:
    print("Training history not found. Setting default best checkpoint info.")
    best_checkpoint = f"{OUTPUT_DIR}/best"
    best_eval_loss = 1.9990 # Default value from previous output
    total_steps = 5000 # Default value from previous output

# --- Define batch sizes for inference (from cell 0-siv7-7aI6W content) ---
# Assuming vram_gb is still in scope from cell uiG9CbqjaD9q. If not, re-declare it.
if 'vram_gb' not in locals():
    vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"Re-initialized vram_gb: {vram_gb:.0f} GB")

if vram_gb >= 70:
    BATCH_SHORT = 128
    BATCH_LONG  = 64
elif vram_gb >= 40:
    BATCH_SHORT = 32
    BATCH_LONG  = 16
else:
    BATCH_SHORT = 8
    BATCH_LONG  = 4

print(f"VRAM: {torch.cuda.memory_allocated() / 1e9:.2f} GB after loading model")
print(f"inference batch sizes: short={BATCH_SHORT}, long={BATCH_LONG}")

# Verify other datasets are loaded for evaluation
if 'test_sells' not in locals():
    from datasets import load_from_disk
    ROOT = "/content/drive/MyDrive/Gatekeepn't/Data/processed"
    test_sells    = load_from_disk(f"{ROOT}/test_sells")
    test_medlane  = load_from_disk(f"{ROOT}/test_medlane")
    test_cochrane = load_from_disk(f"{ROOT}/test_cochrane")
    test_plaba    = load_from_disk(f"{ROOT}/test_plaba")
    print("Test datasets reloaded.")

# Verify spacy model is loaded for entity extraction
if 'ent_nlp' not in locals():
    import spacy
    ent_nlp = spacy.load("en_core_sci_lg")
    print("Spacy model 'en_core_sci_lg' reloaded.")

import os, json, gc, time, random, warnings, torch, numpy as np, spacy, textstat
from datasets import load_from_disk
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,
    Trainer, TrainingArguments, EarlyStoppingCallback,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from bert_score import BERTScorer
from easse.sari import corpus_sari
from datetime import datetime
from google.colab import drive
from huggingface_hub import login

warnings.filterwarnings("ignore", message=".*`do_sample` is set to `False`.*")
drive.mount("/content/drive")

# ── Seeding ──────────────────────────────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
from transformers import set_seed
set_seed(SEED)

HF_TOKEN = "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"
login(token=HF_TOKEN)

ROOT        = "/content/drive/MyDrive/Gatekeepn't/Data/processed"
RESULTS_DIR = "/content/drive/MyDrive/Gatekeepn't/results"
OUTPUT_DIR  = "/content/drive/MyDrive/Gatekeepn't/models/exp3a_mixed_1024"
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

MAX_SEQ_LENGTH = 1024

# ── Training data: MIXED (SELLS + MedLane + Cochrane) ────────
train_ds = load_from_disk(f"{ROOT}/mixed_train")
val_ds   = load_from_disk(f"{ROOT}/combined_val")

print(f"train: {len(train_ds)} (mixed)")
print(f"val:   {len(val_ds)} (combined)")
print(f"train domains: {set(train_ds['domain'])}")
print(f"train datasets: {set(train_ds['dataset'])}")

# ── Test sets ────────────────────────────────────────────────
test_sells    = load_from_disk(f"{ROOT}/test_sells")
test_medlane  = load_from_disk(f"{ROOT}/test_medlane")
test_cochrane = load_from_disk(f"{ROOT}/test_cochrane")
test_plaba    = load_from_disk(f"{ROOT}/test_plaba")

ent_nlp = spacy.load("en_core_sci_lg")

# ── Model: 4-bit QLoRA (identical to Exp 2) ─────────────────
MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

tok = AutoTokenizer.from_pretrained(MODEL_ID, token=HF_TOKEN)
tok.pad_token    = tok.eos_token
tok.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
    token=HF_TOKEN,
)
model = prepare_model_for_kbit_training(model)

# ── LoRA (identical to Exp 2) ────────────────────────────────
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

gpu_name = torch.cuda.get_device_name(0)
vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"\nGPU : {gpu_name} ({vram_gb:.0f} GB)")
print(f"VRAM: {torch.cuda.memory_allocated() / 1e9:.2f} GB after model + LoRA")

# ── Manual response-only masking ─────────────────────────────
# We bypass TRL's masking entirely. Instead:
#   1. Tokenize full conversation (prompt + response) via chat template
#   2. Tokenize prompt-only with add_generation_prompt=True
#   3. Use prompt length to set labels=-100 for prompt tokens
#
# BPE is greedy left-to-right, so prompt tokens are identical
# whether or not the response follows. No boundary mismatch.

def tokenize_and_mask(example):
    messages_full = [
        {"role": "user", "content": example["prompt"]},
        {"role": "assistant", "content": example["response"]},
    ]
    messages_prompt = [
        {"role": "user", "content": example["prompt"]},
    ]

    # Tokenize full conversation (return_dict=False → plain list of ints)
    full_ids = tok.apply_chat_template(
        messages_full, tokenize=True, add_generation_prompt=False,
        return_dict=False,
    )

    # Tokenize prompt only (includes assistant header via add_generation_prompt)
    prompt_ids = tok.apply_chat_template(
        messages_prompt, tokenize=True, add_generation_prompt=True,
        return_dict=False,
    )

    # Truncate to max_length
    full_ids = full_ids[:MAX_SEQ_LENGTH]
    prompt_len = min(len(prompt_ids), len(full_ids))

    # Labels: -100 for prompt tokens, actual token ids for response tokens
    labels = [-100] * prompt_len + full_ids[prompt_len:]

    return {
        "input_ids": full_ids,
        "attention_mask": [1] * len(full_ids),
        "labels": labels,
    }

print("tokenizing train...")
train_tokenized = train_ds.map(
    tokenize_and_mask,
    remove_columns=train_ds.column_names,
    writer_batch_size=1000,
    desc="tokenizing train",
)

print("tokenizing val...")
val_tokenized = val_ds.map(
    tokenize_and_mask,
    remove_columns=val_ds.column_names,
    writer_batch_size=1000,
    desc="tokenizing val",
)

print(f"\ntrain: {len(train_tokenized)} examples")
print(f"val:   {len(val_tokenized)} examples")
print(f"columns: {train_tokenized.column_names}")

# ── Verify masking is correct before burning compute ─────────
print("=" * 60)
print("  SANITY CHECK — response-only masking")
print("=" * 60)

# Check 3 examples from different domains
for i, domain in enumerate(["sells", "medlane", "cochrane"]):
    # Find an example from this domain
    idx = next(j for j, ex in enumerate(train_ds) if ex["dataset"] == domain)
    raw = train_ds[idx]
    tok_ex = train_tokenized[idx]

    input_ids = tok_ex["input_ids"]
    labels = tok_ex["labels"]
    n_total = len(input_ids)
    n_masked = sum(1 for l in labels if l == -100)
    n_trained = n_total - n_masked

    # Decode prompt portion and response portion separately
    prompt_tokens = [input_ids[j] for j in range(n_masked)]
    response_tokens = [input_ids[j] for j in range(n_masked, n_total)]

    decoded_prompt = tok.decode(prompt_tokens, skip_special_tokens=False)
    decoded_response = tok.decode(response_tokens, skip_special_tokens=True)

    print(f"\n{'─' * 55}")
    print(f"  [{domain.upper()}] example {idx}")
    print(f"  total tokens: {n_total}")
    print(f"  masked (prompt): {n_masked}")
    print(f"  trained (response): {n_trained}")
    print(f"  trained %: {n_trained / n_total * 100:.1f}%")
    print(f"  prompt ends with: ...{decoded_prompt[-80:]}")
    print(f"  response starts with: {decoded_response[:80]}...")

    # Verify the response matches the original target
    target_start = raw["response"][:50]
    assert target_start[:30] in decoded_response[:100], (
        f"MISMATCH: response doesn't match target for {domain}!\n"
        f"  expected: {target_start[:50]}\n"
        f"  got: {decoded_response[:50]}"
    )

# Check a full batch via the collator
collator = DataCollatorForSeq2Seq(tokenizer=tok, padding=True)
sample_batch = collator([train_tokenized[i] for i in range(4)])

batch_labels = sample_batch["labels"]
for i in range(4):
    n_total = (batch_labels[i] != tok.pad_token_id).sum().item()
    n_masked = (batch_labels[i] == -100).sum().item()
    n_pad = (batch_labels[i] == tok.pad_token_id).sum().item()
    n_trained = batch_labels[i].shape[0] - n_masked - n_pad
    print(f"\n  batch item {i}: total={batch_labels[i].shape[0]}, "
          f"masked={n_masked}, pad={n_pad}, trained={n_trained}")

assert all(
    (batch_labels[i] != -100).any() for i in range(4)
), "ERROR: some examples have ALL tokens masked — masking is broken!"

print(f"\n{'=' * 60}")
print("  ALL CHECKS PASSED — safe to train")
print(f"{'=' * 60}")

from transformers import DataCollatorForSeq2Seq

# ── Training arguments (identical hyperparameters to Exp 2) ──
# 239k examples / effective_batch_64 ≈ 3,740 steps per epoch

collator = DataCollatorForSeq2Seq(tokenizer=tok, padding=True)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=4,  # effective batch = 16 × 4 = 64
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    weight_decay=0.01,
    bf16=True,
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    seed=SEED,
    data_seed=SEED,
    dataloader_num_workers=2,
    max_grad_norm=1.0,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

print(f"trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
print(f"steps/epoch:      ~{len(train_tokenized) // (16 * 4):,}")
print(f"eval every:       500 steps")
print(f"early stopping:   patience=3 (1,500 steps)")

# ── Resume or start fresh ────────────────────────────────────
resume = False
if os.path.isdir(OUTPUT_DIR):
    checkpoints = [d for d in os.listdir(OUTPUT_DIR) if d.startswith("checkpoint")]
    if checkpoints:
        resume = True
        print(f"found {len(checkpoints)} checkpoint(s) — resuming training")

train_result = trainer.train(resume_from_checkpoint=resume if resume else None)

# ── Save best model ──────────────────────────────────────────
trainer.save_model(f"{OUTPUT_DIR}/best")
tok.save_pretrained(f"{OUTPUT_DIR}/best")

metrics = train_result.metrics
metrics["train_samples"] = len(train_tokenized)
trainer.log_metrics("train", metrics)

print(f"\ntraining complete.")
print(f"best checkpoint: {trainer.state.best_model_checkpoint}")
print(f"best eval loss:  {trainer.state.best_metric:.4f}")
print(f"total steps:     {trainer.state.global_step}")
print(f"saved to:        {OUTPUT_DIR}/best")

# ── Save training history (before trainer gets deleted) ──────
history_path = f"{RESULTS_DIR}/exp3a_train_history.json"
with open(history_path, "w") as f:
    json.dump(trainer.state.log_history, f, indent=2)
print(f"saved train log → {history_path}")

# ── Save trainer state for Cell 9 ────────────────────────────
best_checkpoint = trainer.state.best_model_checkpoint
best_eval_loss = round(trainer.state.best_metric, 4)
total_steps = trainer.state.global_step

# ── Inference helpers (identical to Exp 1 and Exp 2) ─────────
PREFIXES = {
    "sells": "[BIOMED]",  "medlane": "[CLINICAL]",
    "cochrane": "[REVIEW]", "plaba": "[BIOMED]",
}
SAVE_EVERY_N_BATCHES = 5


def predict_batched(ds, batch_size, save_path=None):
    preds = []
    if save_path and os.path.exists(save_path):
        with open(save_path, "r") as f:
            preds = json.load(f)
        print(f"  resuming from {len(preds)}/{len(ds)}")

    start = len(preds)
    total = len(ds)
    if start >= total:
        print(f"  already complete ({total}/{total})")
        return preds

    tok.padding_side = "left"
    empty_count = 0
    t0 = time.time()

    for i in range(start, total, batch_size):
        end   = min(i + batch_size, total)
        batch = ds[i:end]

        prompts = []
        for src, d in zip(batch["source"], batch["dataset"]):
            instruction = (
                f"{PREFIXES[d]} Simplify the following medical text into plain "
                f"language that a patient without medical training can "
                f"understand:\n\n{src}"
            )
            prompts.append(tok.apply_chat_template(
                [{"role": "user", "content": instruction}],
                add_generation_prompt=True,
                tokenize=False,
            ))

        encoded   = tok(prompts, return_tensors="pt", padding=True).to(model.device)
        input_len = encoded["input_ids"].shape[1]

        with torch.no_grad():
            out = model.generate(
                **encoded,
                max_new_tokens=1024,
                do_sample=False,
                repetition_penalty=1.1,
                pad_token_id=tok.pad_token_id,
            )

        for j in range(out.shape[0]):
            text = tok.decode(out[j][input_len:], skip_special_tokens=True).strip()
            if not text:
                text = "[EMPTY]"
                empty_count += 1
            preds.append(text)

        batch_num = (i - start) // batch_size + 1
        elapsed   = time.time() - t0
        rate      = (end - start) / elapsed if elapsed > 0 else 0
        eta       = (total - end) / rate if rate > 0 else 0
        warn      = f"  [EMPTY: {empty_count}]" if empty_count else ""
        print(f"  {end:>6}/{total}  |  {rate:.1f} ex/s  |  ETA {eta / 60:.0f}m{warn}")

        if batch_num % SAVE_EVERY_N_BATCHES == 0 or end == total:
            if save_path:
                with open(save_path, "w") as f:
                    json.dump(preds, f)

    tok.padding_side = "right"
    if empty_count:
        print(f"  WARNING: {empty_count}/{total} empty predictions")
    return preds


def per_example_sari(srcs, preds, refs):
    return [corpus_sari([s], [p], [[r]]) for s, p, r in zip(srcs, preds, refs)]


def per_example_entity(srcs, preds):
    src_ents  = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(srcs, batch_size=512)]
    pred_ents = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(preds, batch_size=512)]
    ps, rs, f1s = [], [], []
    for s_set, p_set in zip(src_ents, pred_ents):
        overlap = len(p_set & s_set)
        if len(p_set) == 0 and len(s_set) == 0:
            p, r = 1.0, 1.0
        elif len(p_set) == 0:
            p, r = 0.0, 0.0
        elif len(s_set) == 0:
            p, r = 0.0, 1.0
        else:
            p = overlap / len(p_set)
            r = overlap / len(s_set)
        f = (2 * p * r / (p + r)) if (p + r) > 0 else 0.0
        ps.append(p); rs.append(r); f1s.append(f)
    return ps, rs, f1s


def per_example_readability(srcs, preds):
    fre_d, fkg_d, valid_idx = [], [], []
    for i, (src, pred) in enumerate(zip(srcs, preds)):
        s, p = src.strip(), pred.strip()
        if s and p and p != "[EMPTY]":
            fre_d.append(textstat.flesch_reading_ease(p)
                         - textstat.flesch_reading_ease(s))
            fkg_d.append(textstat.flesch_kincaid_grade(p)
                         - textstat.flesch_kincaid_grade(s))
            valid_idx.append(i)
    return fre_d, fkg_d, valid_idx


def bootstrap_mean_ci(scores, n_boot=1000, ci=95):
    arr = np.array(scores)
    rng = np.random.RandomState(SEED)
    n   = len(arr)
    means = [arr[rng.randint(0, n, size=n)].mean() for _ in range(n_boot)]
    lo = np.percentile(means, (100 - ci) / 2)
    hi = np.percentile(means, 100 - (100 - ci) / 2)
    return round(float(lo), 4), round(float(hi), 4)


def evaluate(tag, ds, preds, scorer):
    srcs = list(ds["source"])
    refs = list(ds["target"])
    n    = len(ds)

    print(f"\n{'─' * 55}")
    print(f"  {tag.upper()} ({n} examples)")
    print(f"{'─' * 55}")

    print("  SARI (per-sentence) ...")
    sari_scores = per_example_sari(srcs, preds, refs)

    print("  BERTScore ...")
    _, _, bs_f1 = scorer.score(preds, refs)
    bert_scores = bs_f1.tolist()

    print("  Entity P/R/F1 ...")
    ep_scores, er_scores, ef1_scores = per_example_entity(srcs, preds)

    print("  Readability ...")
    fre_d, fkg_d, read_idx = per_example_readability(srcs, preds)

    result = dict(
        n=n,
        sari=round(float(np.mean(sari_scores)), 2),
        bert_f1=round(float(np.mean(bert_scores)), 4),
        ent_p=round(float(np.mean(ep_scores)), 4),
        ent_r=round(float(np.mean(er_scores)), 4),
        ent_f1=round(float(np.mean(ef1_scores)), 4),
        d_fre=round(float(np.mean(fre_d)), 2),
        d_fkg=round(float(np.mean(fkg_d)), 2),
        n_empty=sum(1 for p in preds if p == "[EMPTY]"),
        n_read=len(read_idx),
    )

    print("  Bootstrap CIs (1000 resamples) ...")
    result["sari_ci"]    = bootstrap_mean_ci(sari_scores)
    result["bert_f1_ci"] = bootstrap_mean_ci(bert_scores)
    result["ent_f1_ci"]  = bootstrap_mean_ci(ef1_scores)
    result["d_fre_ci"]   = bootstrap_mean_ci(fre_d)

    print(f"  SARI  = {result['sari']:.2f}  {result['sari_ci']}")
    print(f"  BS    = {result['bert_f1']:.4f}  {result['bert_f1_ci']}")
    print(f"  EntP  = {result['ent_p']:.4f}  |  EntR = {result['ent_r']:.4f}  "
          f"|  EntF1 = {result['ent_f1']:.4f}  {result['ent_f1_ci']}")
    print(f"  dFRE  = {result['d_fre']:+.2f}  {result['d_fre_ci']}  |  "
          f"dFKG = {result['d_fkg']:+.2f}")
    if result["n_empty"]:
        print(f"  ⚠ {result['n_empty']} empty predictions")

    per_ex = dict(
        sari=sari_scores, bert_f1=bert_scores,
        ent_p=ep_scores, ent_r=er_scores, ent_f1=ef1_scores,
    )
    return result, per_ex


def print_summary(results, tags):
    print(f"\n{'dataset':<11} {'SARI':>6} {'95% CI':>14} {'BS':>7} "
          f"{'EntP':>6} {'EntR':>6} {'EntF1':>6} {'95% CI':>14} "
          f"{'dFRE':>6} {'dFKG':>6}")
    print("─" * 105)
    for tag in tags:
        r = results[tag]
        sci = f"[{r['sari_ci'][0]:.2f},{r['sari_ci'][1]:.2f}]"
        eci = f"[{r['ent_f1_ci'][0]:.4f},{r['ent_f1_ci'][1]:.4f}]"
        print(f"{tag:<11} {r['sari']:>6.2f} {sci:>14} {r['bert_f1']:>7.4f} "
              f"{r['ent_p']:>6.4f} {r['ent_r']:>6.4f} {r['ent_f1']:>6.4f} "
              f"{eci:>14} {r['d_fre']:>+6.2f} {r['d_fkg']:>+6.2f}")


# ── Generate predictions ─────────────────────────────────────
all_preds = {}

for tag, ds, bs in [
    ("sells",    test_sells,    BATCH_SHORT),
    ("medlane",  test_medlane,  BATCH_SHORT),
    ("cochrane", test_cochrane, BATCH_LONG),
    ("plaba",    test_plaba,    BATCH_SHORT),
]:
    save_path = f"{RESULTS_DIR}/exp3a_preds_{tag}.json"
    print(f"\n{'=' * 55}")
    print(f"  {tag.upper()} — {len(ds)} examples, batch={bs}")
    print(f"{'=' * 55}")
    all_preds[tag] = predict_batched(ds, batch_size=bs, save_path=save_path)

print(f"\nall predictions complete.")

scorer = BERTScorer(
    model_type="allenai/scibert_scivocab_uncased",
    batch_size=128,
    device="cuda:0",
)
scorer._tokenizer.model_max_length = 512

# reload from drive if kernel restarted
for tag in ["sells", "medlane", "cochrane", "plaba"]:
    if tag not in all_preds:
        path = f"{RESULTS_DIR}/exp3a_preds_{tag}.json"
        with open(path, "r") as f:
            all_preds[tag] = json.load(f)
        print(f"  loaded {tag} from drive")

results     = {}
per_example = {}

print("=" * 60)
print("  TIER 1 — IN-DOMAIN")
print("=" * 60)

for tag, ds in [("sells", test_sells), ("medlane", test_medlane),
                ("cochrane", test_cochrane)]:
    results[tag], per_example[tag] = evaluate(tag, ds, all_preds[tag], scorer)

print("\n" + "=" * 60)
print("  TIER 2 — OUT-OF-DISTRIBUTION BIOMEDICAL")
print("=" * 60)

results["plaba"], per_example["plaba"] = evaluate(
    "plaba", test_plaba, all_preds["plaba"], scorer)

print_summary(results, ["sells", "medlane", "cochrane", "plaba"])

# Verify per-sentence SARI mean matches corpus-level SARI
print("\nSARI verification (per-sentence mean vs corpus-level):")
for tag in ["sells", "medlane", "cochrane", "plaba"]:
    ds_ref = {"sells": test_sells, "medlane": test_medlane,
              "cochrane": test_cochrane, "plaba": test_plaba}[tag]
    corpus = corpus_sari(list(ds_ref["source"]), all_preds[tag], [list(ds_ref["target"])])
    print(f"  {tag}: per-sentence={results[tag]['sari']:.2f}, corpus={corpus:.2f}")

output = {
    "experiment": "exp3a_mixed_1024",
    "timestamp": datetime.now().isoformat(),
    "description": (
        "Llama 3.1 8B Instruct + QLoRA, fine-tuned on SELLS+MedLane+Cochrane mixed, "
        "4-bit NF4 training, bf16 inference (merged), SDPA, response-only masking, "
        "bootstrap 95% CIs (n=1000, seed=42)"
    ),
    "model": MODEL_ID,
    "gpu": torch.cuda.get_device_name(0),
    "vram_gb": round(vram_gb, 1),
    "training_precision": "4-bit NF4 (bf16 compute, QLoRA)",
    "inference_precision": "bf16 (LoRA merged into base, same as Exp 1)",
    "attn_implementation": "sdpa",
    "seed": SEED,
    "training_config": {
        "train_data": "SELLS + MedLane + Cochrane (T=2 temperature mixed)",
        "train_size": len(train_ds),
        "val_size": len(val_ds),
        "max_seq_length": MAX_SEQ_LENGTH,
        "response_only_masking": True,
        "lora_r": 16,
        "lora_alpha": 32,
        "lora_dropout": 0.05,
        "learning_rate": 2e-4,
        "effective_batch_size": 64,
        "num_epochs_set": 3,
        "best_step": best_checkpoint,
        "best_eval_loss": best_eval_loss,
        "total_steps": total_steps,
    },
    "generation_config": {
        "max_new_tokens": 1024,
        "do_sample": False,
        "repetition_penalty": 1.1,
    },
    "test_sizes": {
        t: len(d) for t, d in [("sells", test_sells), ("medlane", test_medlane),
                                ("cochrane", test_cochrane), ("plaba", test_plaba)]
    },
    "library_versions": {
        "transformers": __import__("transformers").__version__,
        "torch": torch.__version__,
        "peft": __import__("peft").__version__,
        "trl": __import__("trl").__version__,
        "bitsandbytes": __import__("bitsandbytes").__version__,
        "datasets": __import__("datasets").__version__,
        "bert_score": __import__("bert_score").__version__,
    },
    "results": results,
}

path = f"{RESULTS_DIR}/exp3a_mixed_1024.json"
with open(path, "w") as f:
    json.dump(output, f, indent=2)
print(f"saved results     → {path}")

path_pe = f"{RESULTS_DIR}/exp3a_per_example.json"
with open(path_pe, "w") as f:
    json.dump(per_example, f)
print(f"saved per-example → {path_pe}")

print("\n" + "=" * 60)
print("  FINAL RESULTS — EXP 3a MIXED TRAINING (1024)")
print("=" * 60)
print_summary(results, ["sells", "medlane", "cochrane", "plaba"])