# -*- coding: utf-8 -*-
"""Exp_02-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0tDA4Gnsq2ZKNEZgS374kRkenpR6f_a

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
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q git+https://github.com/feralvam/easse.git
!pip install -q transformers peft bitsandbytes accelerate datasets \
    sentencepiece protobuf bert-score textstat scispacy
!pip install -q https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_lg-0.5.4.tar.gz

!pip freeze | grep -E "transformers|peft|bitsandbytes|accelerate|datasets|bert.score|textstat|torch"

import os; os.kill(os.getpid(), 9)

import os, json, gc, time, random, warnings, torch, numpy as np, spacy, textstat
from datasets import load_from_disk
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,
    Trainer, TrainingArguments, EarlyStoppingCallback,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from bert_score import BERTScorer
from easse.sari import corpus_sari
from datetime import datetime
from google.colab import drive, userdata
from huggingface_hub import login

warnings.filterwarnings("ignore", message=".*`do_sample` is set to `False`.*")
drive.mount("/content/drive")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
from transformers import set_seed
set_seed(SEED)

# Retrieve HF_TOKEN from Colab secrets
HF_TOKEN = userdata.get("HF_TOKEN")  # Fetch token securely from Colab secrets
login(token=HF_TOKEN)

ROOT        = "/content/drive/MyDrive/Gatekeepn't/Data/processed"
RESULTS_DIR = "/content/drive/MyDrive/Gatekeepn't/results"
OUTPUT_DIR  = "/content/drive/MyDrive/Gatekeepn't/models/exp2v2_sells_only"
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

MAX_SEQ_LENGTH = 1024  # same as Exp 3a

# ── Training data: SELLS ONLY ────────────────────────────────
train_ds = load_from_disk(f"{ROOT}/raw_train_sells")
combined_val = load_from_disk(f"{ROOT}/combined_val")
val_ds = combined_val.filter(lambda x: x["dataset"] == "sells")

print(f"train: {len(train_ds)} (SELLS only)")
print(f"val:   {len(val_ds)} (SELLS only)")

# ── Test sets ────────────────────────────────────────────────
test_sells    = load_from_disk(f"{ROOT}/test_sells")
test_medlane  = load_from_disk(f"{ROOT}/test_medlane")
test_cochrane = load_from_disk(f"{ROOT}/test_cochrane")
test_plaba    = load_from_disk(f"{ROOT}/test_plaba")

ent_nlp = spacy.load("en_core_sci_lg")

# ── Model: 4-bit QLoRA (identical to Exp 3a) ────────────────
MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

tok = AutoTokenizer.from_pretrained(MODEL_ID, token=HF_TOKEN)
tok.pad_token    = tok.eos_token
tok.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
    token=HF_TOKEN,
)
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

gpu_name = torch.cuda.get_device_name(0)
vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"\nGPU : {gpu_name} ({vram_gb:.0f} GB)")
print(f"VRAM: {torch.cuda.memory_allocated() / 1e9:.2f} GB after model + LoRA")

# ── Manual response-only masking (identical to Exp 3a) ───────

def tokenize_and_mask(example):
    messages_full = [
        {"role": "user", "content": example["prompt"]},
        {"role": "assistant", "content": example["response"]},
    ]
    messages_prompt = [
        {"role": "user", "content": example["prompt"]},
    ]

    # Tokenize full conversation (return_dict=False → plain list of ints)
    full_ids = tok.apply_chat_template(
        messages_full, tokenize=True, add_generation_prompt=False,
        return_dict=False,
    )

    # Tokenize prompt only (includes assistant header via add_generation_prompt)
    prompt_ids = tok.apply_chat_template(
        messages_prompt, tokenize=True, add_generation_prompt=True,
        return_dict=False,
    )

    # Truncate to max_length
    full_ids = full_ids[:MAX_SEQ_LENGTH]
    prompt_len = min(len(prompt_ids), len(full_ids))

    # Labels: -100 for prompt tokens, actual token ids for response tokens
    labels = [-100] * prompt_len + full_ids[prompt_len:]

    return {
        "input_ids": full_ids,
        "attention_mask": [1] * len(full_ids),
        "labels": labels,
    }

print("tokenizing train...")
train_tokenized = train_ds.map(
    tokenize_and_mask,
    remove_columns=train_ds.column_names,
    writer_batch_size=1000,
    desc="tokenizing train",
)

print("tokenizing val...")
val_tokenized = val_ds.map(
    tokenize_and_mask,
    remove_columns=val_ds.column_names,
    writer_batch_size=1000,
    desc="tokenizing val",
)

print(f"\ntrain: {len(train_tokenized)} examples")
print(f"val:   {len(val_tokenized)} examples")
print(f"columns: {train_tokenized.column_names}")

# ── Quick structure check ────────────────────────────────────
ex = train_tokenized[0]
print(f"\ntype of input_ids: {type(ex['input_ids'])}")
print(f"input_ids length: {len(ex['input_ids'])}")
print(f"labels length: {len(ex['labels'])}")
print(f"masked tokens: {sum(1 for l in ex['labels'] if l == -100)}")
print(f"trained tokens: {sum(1 for l in ex['labels'] if l != -100)}")
print(f"first few input_ids: {ex['input_ids'][:5]}")

assert len(ex['input_ids']) == len(ex['labels']), "length mismatch!"
assert all(isinstance(x, int) for x in ex['input_ids'][:10]), "input_ids not plain ints!"
assert sum(1 for l in ex['labels'] if l != -100) > 0, "no trained tokens!"
print("structure OK")

print("=" * 60)
print("  SANITY CHECK — response-only masking (SELLS only)")
print("=" * 60)

# Check 3 examples at different positions
for i, idx in enumerate([0, len(train_ds) // 2, len(train_ds) - 1]):
    raw = train_ds[idx]
    tok_ex = train_tokenized[idx]

    input_ids = tok_ex["input_ids"]
    labels = tok_ex["labels"]
    n_total = len(input_ids)
    n_masked = sum(1 for l in labels if l == -100)
    n_trained = n_total - n_masked

    prompt_tokens = [input_ids[j] for j in range(n_masked)]
    response_tokens = [input_ids[j] for j in range(n_masked, n_total)]

    decoded_prompt = tok.decode(prompt_tokens, skip_special_tokens=False)
    decoded_response = tok.decode(response_tokens, skip_special_tokens=True)

    print(f"\n{'─' * 55}")
    print(f"  example {idx}")
    print(f"  total tokens: {n_total}")
    print(f"  masked (prompt): {n_masked}")
    print(f"  trained (response): {n_trained}")
    print(f"  trained %: {n_trained / n_total * 100:.1f}%")
    print(f"  prompt ends with: ...{decoded_prompt[-80:]}")
    print(f"  response starts with: {decoded_response[:80]}...")

    target_start = raw["response"][:30]
    assert target_start in decoded_response[:100], (
        f"MISMATCH at idx {idx}!\n"
        f"  expected: {target_start}\n"
        f"  got: {decoded_response[:50]}"
    )

# Batch check via collator
collator = DataCollatorForSeq2Seq(tokenizer=tok, padding=True)
sample_batch = collator([train_tokenized[i] for i in range(4)])
print(f"\nlabel_pad_token_id: {collator.label_pad_token_id}")

batch_labels = sample_batch["labels"]
for i in range(4):
    n_masked = (batch_labels[i] == -100).sum().item()
    n_pad = (batch_labels[i] == collator.label_pad_token_id).sum().item() if collator.label_pad_token_id != -100 else 0
    n_trained = batch_labels[i].shape[0] - n_masked - n_pad
    print(f"  batch item {i}: total={batch_labels[i].shape[0]}, "
          f"masked={n_masked}, trained={n_trained}")

assert all(
    (batch_labels[i] != -100).any() for i in range(4)
), "ERROR: some examples have ALL tokens masked!"

print(f"\n{'=' * 60}")
print("  ALL CHECKS PASSED — safe to train")
print(f"{'=' * 60}")

# ── Training (identical hyperparameters to Exp 3a) ───────────
# 168k examples / effective_batch_64 ≈ 2,628 steps per epoch

collator = DataCollatorForSeq2Seq(tokenizer=tok, padding=True)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=4,  # effective batch = 16 × 4 = 64
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    weight_decay=0.01,
    bf16=True,
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    seed=SEED,
    data_seed=SEED,
    dataloader_num_workers=2,
    max_grad_norm=1.0,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

print(f"trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
print(f"steps/epoch:      ~{len(train_tokenized) // (16 * 4):,}")
print(f"eval every:       500 steps")
print(f"early stopping:   patience=3 (1,500 steps)")

# ── Resume or start fresh ────────────────────────────────────
resume = False
if os.path.isdir(OUTPUT_DIR):
    checkpoints = [d for d in os.listdir(OUTPUT_DIR) if d.startswith("checkpoint")]
    if checkpoints:
        resume = True
        print(f"found {len(checkpoints)} checkpoint(s) — resuming training")

train_result = trainer.train(resume_from_checkpoint=resume if resume else None)

trainer.save_model(f"{OUTPUT_DIR}/best")
tok.save_pretrained(f"{OUTPUT_DIR}/best")

metrics = train_result.metrics
metrics["train_samples"] = len(train_tokenized)
trainer.log_metrics("train", metrics)

print(f"\ntraining complete.")
print(f"best checkpoint: {trainer.state.best_model_checkpoint}")
print(f"best eval loss:  {trainer.state.best_metric:.4f}")
print(f"total steps:     {trainer.state.global_step}")
print(f"saved to:        {OUTPUT_DIR}/best")

history_path = f"{RESULTS_DIR}/exp2v2_train_history.json"
with open(history_path, "w") as f:
    json.dump(trainer.state.log_history, f, indent=2)
print(f"saved train log → {history_path}")

best_checkpoint = trainer.state.best_model_checkpoint
best_eval_loss = round(trainer.state.best_metric, 4)
total_steps = trainer.state.global_step

from peft import AutoPeftModelForCausalLM

del model
del trainer
gc.collect()
torch.cuda.empty_cache()
print(f"VRAM after cleanup: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

print("merging LoRA weights into base model...")
merged_path = f"{OUTPUT_DIR}/merged_bf16"

peft_model = AutoPeftModelForCausalLM.from_pretrained(
    f"{OUTPUT_DIR}/best",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    device_map="auto",
    token=HF_TOKEN,
)
merged_model = peft_model.merge_and_unload()
merged_model.save_pretrained(merged_path)
tok.save_pretrained(merged_path)

del peft_model
del merged_model
gc.collect()
torch.cuda.empty_cache()

print("loading merged bf16 model for inference...")
model = AutoModelForCausalLM.from_pretrained(
    merged_path,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
)
model.eval()

print(f"VRAM: {torch.cuda.memory_allocated() / 1e9:.2f} GB (bf16, same as Exp 1)")

if vram_gb >= 70:
    BATCH_SHORT = 128
    BATCH_LONG  = 64
elif vram_gb >= 40:
    BATCH_SHORT = 32
    BATCH_LONG  = 16
else:
    BATCH_SHORT = 8
    BATCH_LONG  = 4

print(f"inference batch sizes: short={BATCH_SHORT}, long={BATCH_LONG}")

PREFIXES = {
    "sells": "[BIOMED]",  "medlane": "[CLINICAL]",
    "cochrane": "[REVIEW]", "plaba": "[BIOMED]",
}
SAVE_EVERY_N_BATCHES = 5


def predict_batched(ds, batch_size, save_path=None):
    preds = []
    if save_path and os.path.exists(save_path):
        with open(save_path, "r") as f:
            preds = json.load(f)
        print(f"  resuming from {len(preds)}/{len(ds)}")

    start = len(preds)
    total = len(ds)
    if start >= total:
        print(f"  already complete ({total}/{total})")
        return preds

    tok.padding_side = "left"
    empty_count = 0
    t0 = time.time()

    for i in range(start, total, batch_size):
        end   = min(i + batch_size, total)
        batch = ds[i:end]

        prompts = []
        for src, d in zip(batch["source"], batch["dataset"]):
            instruction = (
                f"{PREFIXES[d]} Simplify the following medical text into plain "
                f"language that a patient without medical training can "
                f"understand:\n\n{src}"
            )
            prompts.append(tok.apply_chat_template(
                [{"role": "user", "content": instruction}],
                add_generation_prompt=True,
                tokenize=False,
            ))

        encoded   = tok(prompts, return_tensors="pt", padding=True).to(model.device)
        input_len = encoded["input_ids"].shape[1]

        with torch.no_grad():
            out = model.generate(
                **encoded,
                max_new_tokens=1024,
                do_sample=False,
                repetition_penalty=1.1,
                pad_token_id=tok.pad_token_id,
            )

        for j in range(out.shape[0]):
            text = tok.decode(out[j][input_len:], skip_special_tokens=True).strip()
            if not text:
                text = "[EMPTY]"
                empty_count += 1
            preds.append(text)

        batch_num = (i - start) // batch_size + 1
        elapsed   = time.time() - t0
        rate      = (end - start) / elapsed if elapsed > 0 else 0
        eta       = (total - end) / rate if rate > 0 else 0
        warn      = f"  [EMPTY: {empty_count}]" if empty_count else ""
        print(f"  {end:>6}/{total}  |  {rate:.1f} ex/s  |  ETA {eta / 60:.0f}m{warn}")

        if batch_num % SAVE_EVERY_N_BATCHES == 0 or end == total:
            if save_path:
                with open(save_path, "w") as f:
                    json.dump(preds, f)

    tok.padding_side = "right"
    if empty_count:
        print(f"  WARNING: {empty_count}/{total} empty predictions")
    return preds


def per_example_sari(srcs, preds, refs):
    return [corpus_sari([s], [p], [[r]]) for s, p, r in zip(srcs, preds, refs)]


def per_example_entity(srcs, preds):
    src_ents  = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(srcs, batch_size=512)]
    pred_ents = [set(e.text.lower() for e in doc.ents)
                 for doc in ent_nlp.pipe(preds, batch_size=512)]
    ps, rs, f1s = [], [], []
    for s_set, p_set in zip(src_ents, pred_ents):
        overlap = len(p_set & s_set)
        if len(p_set) == 0 and len(s_set) == 0:
            p, r = 1.0, 1.0
        elif len(p_set) == 0:
            p, r = 0.0, 0.0
        elif len(s_set) == 0:
            p, r = 0.0, 1.0
        else:
            p = overlap / len(p_set)
            r = overlap / len(s_set)
        f = (2 * p * r / (p + r)) if (p + r) > 0 else 0.0
        ps.append(p); rs.append(r); f1s.append(f)
    return ps, rs, f1s


def per_example_readability(srcs, preds):
    fre_d, fkg_d, valid_idx = [], [], []
    for i, (src, pred) in enumerate(zip(srcs, preds)):
        s, p = src.strip(), pred.strip()
        if s and p and p != "[EMPTY]":
            fre_d.append(textstat.flesch_reading_ease(p)
                         - textstat.flesch_reading_ease(s))
            fkg_d.append(textstat.flesch_kincaid_grade(p)
                         - textstat.flesch_kincaid_grade(s))
            valid_idx.append(i)
    return fre_d, fkg_d, valid_idx


def bootstrap_mean_ci(scores, n_boot=1000, ci=95):
    arr = np.array(scores)
    rng = np.random.RandomState(SEED)
    n   = len(arr)
    means = [arr[rng.randint(0, n, size=n)].mean() for _ in range(n_boot)]
    lo = np.percentile(means, (100 - ci) / 2)
    hi = np.percentile(means, 100 - (100 - ci) / 2)
    return round(float(lo), 4), round(float(hi), 4)


def evaluate(tag, ds, preds, scorer):
    srcs = list(ds["source"])
    refs = list(ds["target"])
    n    = len(ds)

    print(f"\n{'─' * 55}")
    print(f"  {tag.upper()} ({n} examples)")
    print(f"{'─' * 55}")

    print("  SARI (per-sentence) ...")
    sari_scores = per_example_sari(srcs, preds, refs)

    print("  BERTScore ...")
    _, _, bs_f1 = scorer.score(preds, refs)
    bert_scores = bs_f1.tolist()

    print("  Entity P/R/F1 ...")
    ep_scores, er_scores, ef1_scores = per_example_entity(srcs, preds)

    print("  Readability ...")
    fre_d, fkg_d, read_idx = per_example_readability(srcs, preds)

    result = dict(
        n=n,
        sari=round(float(np.mean(sari_scores)), 2),
        bert_f1=round(float(np.mean(bert_scores)), 4),
        ent_p=round(float(np.mean(ep_scores)), 4),
        ent_r=round(float(np.mean(er_scores)), 4),
        ent_f1=round(float(np.mean(ef1_scores)), 4),
        d_fre=round(float(np.mean(fre_d)), 2),
        d_fkg=round(float(np.mean(fkg_d)), 2),
        n_empty=sum(1 for p in preds if p == "[EMPTY]"),
        n_read=len(read_idx),
    )

    print("  Bootstrap CIs (1000 resamples) ...")
    result["sari_ci"]    = bootstrap_mean_ci(sari_scores)
    result["bert_f1_ci"] = bootstrap_mean_ci(bert_scores)
    result["ent_f1_ci"]  = bootstrap_mean_ci(ef1_scores)
    result["d_fre_ci"]   = bootstrap_mean_ci(fre_d)

    print(f"  SARI  = {result['sari']:.2f}  {result['sari_ci']}")
    print(f"  BS    = {result['bert_f1']:.4f}  {result['bert_f1_ci']}")
    print(f"  EntP  = {result['ent_p']:.4f}  |  EntR = {result['ent_r']:.4f}  "
          f"|  EntF1 = {result['ent_f1']:.4f}  {result['ent_f1_ci']}")
    print(f"  dFRE  = {result['d_fre']:+.2f}  {result['d_fre_ci']}  |  "
          f"dFKG = {result['d_fkg']:+.2f}")
    if result["n_empty"]:
        print(f"  ⚠ {result['n_empty']} empty predictions")

    per_ex = dict(
        sari=sari_scores, bert_f1=bert_scores,
        ent_p=ep_scores, ent_r=er_scores, ent_f1=ef1_scores,
    )
    return result, per_ex


def print_summary(results, tags):
    print(f"\n{'dataset':<11} {'SARI':>6} {'95% CI':>14} {'BS':>7} "
          f"{'EntP':>6} {'EntR':>6} {'EntF1':>6} {'95% CI':>14} "
          f"{'dFRE':>6} {'dFKG':>6}")
    print("─" * 105)
    for tag in tags:
        r = results[tag]
        sci = f"[{r['sari_ci'][0]:.2f},{r['sari_ci'][1]:.2f}]"
        eci = f"[{r['ent_f1_ci'][0]:.4f},{r['ent_f1_ci'][1]:.4f}]"
        print(f"{tag:<11} {r['sari']:>6.2f} {sci:>14} {r['bert_f1']:>7.4f} "
              f"{r['ent_p']:>6.4f} {r['ent_r']:>6.4f} {r['ent_f1']:>6.4f} "
              f"{eci:>14} {r['d_fre']:>+6.2f} {r['d_fkg']:>+6.2f}")


# ── Generate predictions ─────────────────────────────────────
all_preds = {}

for tag, ds, bs in [
    ("sells",    test_sells,    BATCH_SHORT),
    ("medlane",  test_medlane,  BATCH_SHORT),
    ("cochrane", test_cochrane, BATCH_LONG),
    ("plaba",    test_plaba,    BATCH_SHORT),
]:
    save_path = f"{RESULTS_DIR}/exp2v2_preds_{tag}.json"
    print(f"\n{'=' * 55}")
    print(f"  {tag.upper()} — {len(ds)} examples, batch={bs}")
    print(f"{'=' * 55}")
    all_preds[tag] = predict_batched(ds, batch_size=bs, save_path=save_path)

print(f"\nall predictions complete.")

scorer = BERTScorer(
    model_type="allenai/scibert_scivocab_uncased",
    batch_size=128,
    device="cuda:0",
)
scorer._tokenizer.model_max_length = 512

for tag in ["sells", "medlane", "cochrane", "plaba"]:
    if tag not in all_preds:
        path = f"{RESULTS_DIR}/exp2v2_preds_{tag}.json"
        with open(path, "r") as f:
            all_preds[tag] = json.load(f)
        print(f"  loaded {tag} from drive")

results     = {}
per_example = {}

print("=" * 60)
print("  TIER 1 — IN-DOMAIN")
print("=" * 60)

for tag, ds in [("sells", test_sells), ("medlane", test_medlane),
                ("cochrane", test_cochrane)]:
    results[tag], per_example[tag] = evaluate(tag, ds, all_preds[tag], scorer)

print("\n" + "=" * 60)
print("  TIER 2 — OUT-OF-DISTRIBUTION BIOMEDICAL")
print("=" * 60)

results["plaba"], per_example["plaba"] = evaluate(
    "plaba", test_plaba, all_preds["plaba"], scorer)

print_summary(results, ["sells", "medlane", "cochrane", "plaba"])

# SARI verification
print("\nSARI verification (per-sentence mean vs corpus-level):")
for tag in ["sells", "medlane", "cochrane", "plaba"]:
    ds_ref = {"sells": test_sells, "medlane": test_medlane,
              "cochrane": test_cochrane, "plaba": test_plaba}[tag]
    corpus = corpus_sari(list(ds_ref["source"]), all_preds[tag], [list(ds_ref["target"])])
    print(f"  {tag}: per-sentence={results[tag]['sari']:.2f}, corpus={corpus:.2f}")

output = {
    "experiment": "exp2v2_sells_only",
    "timestamp": datetime.now().isoformat(),
    "description": (
        "Llama 3.1 8B Instruct + QLoRA, fine-tuned on SELLS only, "
        "4-bit NF4 training, bf16 inference (merged), SDPA, response-only masking, "
        "bootstrap 95% CIs (n=1000, seed=42). "
        "V2: uses manual response-only masking (standard Trainer) for consistency with Exp 3a."
    ),
    "model": MODEL_ID,
    "gpu": torch.cuda.get_device_name(0),
    "vram_gb": round(vram_gb, 1),
    "training_precision": "4-bit NF4 (bf16 compute, QLoRA)",
    "inference_precision": "bf16 (LoRA merged into base, same as Exp 1)",
    "attn_implementation": "sdpa",
    "seed": SEED,
    "training_config": {
        "train_data": "SELLS only",
        "train_size": len(train_ds),
        "val_size": len(val_ds),
        "max_seq_length": MAX_SEQ_LENGTH,
        "response_only_masking": True,
        "lora_r": 16,
        "lora_alpha": 32,
        "lora_dropout": 0.05,
        "learning_rate": 2e-4,
        "effective_batch_size": 64,
        "num_epochs_set": 3,
        "best_step": best_checkpoint,
        "best_eval_loss": best_eval_loss,
        "total_steps": total_steps,
    },
    "generation_config": {
        "max_new_tokens": 1024,
        "do_sample": False,
        "repetition_penalty": 1.1,
    },
    "test_sizes": {
        t: len(d) for t, d in [("sells", test_sells), ("medlane", test_medlane),
                                ("cochrane", test_cochrane), ("plaba", test_plaba)]
    },
    "library_versions": {
        "transformers": __import__("transformers").__version__,
        "torch": torch.__version__,
        "peft": __import__("peft").__version__,
        "bitsandbytes": __import__("bitsandbytes").__version__,
        "datasets": __import__("datasets").__version__,
        "bert_score": __import__("bert_score").__version__,
    },
    "results": results,
}

path = f"{RESULTS_DIR}/exp2v2_sells_only.json"
with open(path, "w") as f:
    json.dump(output, f, indent=2)
print(f"saved results     → {path}")

path_pe = f"{RESULTS_DIR}/exp2v2_per_example.json"
with open(path_pe, "w") as f:
    json.dump(per_example, f)
print(f"saved per-example → {path_pe}")

print("\n" + "=" * 60)
print("  FINAL RESULTS — EXP 2v2 SELLS-ONLY (response-only masking)")
print("=" * 60)
print_summary(results, ["sells", "medlane", "cochrane", "plaba"])