# -*- coding: utf-8 -*-
"""EDA_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGBDwWauBgNkEaG0wxjkzmptda7QwdKs
"""

!pip install -q textstat datasets matplotlib transformers sentencepiece protobuf

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import textstat
from collections import Counter

from google.colab import drive
drive.mount("/content/drive")

from datasets import load_from_disk

ROOT = "/content/drive/MyDrive/Gatekeepn't/Data/processed"

mixed_train = load_from_disk(f"{ROOT}/mixed_train")
combined_val = load_from_disk(f"{ROOT}/combined_val")
test_sells = load_from_disk(f"{ROOT}/test_sells")
test_medlane = load_from_disk(f"{ROOT}/test_medlane")
test_cochrane = load_from_disk(f"{ROOT}/test_cochrane")
test_plaba = load_from_disk(f"{ROOT}/test_plaba")

print("loaded all splits")
for name, ds in [("train", mixed_train), ("val", combined_val),
                 ("test_sells", test_sells), ("test_medlane", test_medlane),
                 ("test_cochrane", test_cochrane), ("test_plaba", test_plaba)]:
    print(f"  {name}: {len(ds)} rows, columns: {ds.column_names}")

from transformers import AutoTokenizer
from huggingface_hub import login

HF_TOKEN = "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"
login(token=HF_TOKEN)

tok = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct", token=HF_TOKEN)
tok.pad_token = tok.eos_token
tok.padding_side = "right"

def add_token_counts(row):
    instruction = row["prompt"]
    target = row.get("response", row.get("completion", ""))
    messages = [
        {"role": "user", "content": instruction},
        {"role": "assistant", "content": target},
    ]
    full_text = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    return {"n_tokens": len(tok.encode(full_text))}

print("\ntokenizing to get lengths (no model, just tokenizer)...")
mixed_train = mixed_train.map(add_token_counts, num_proc=2)
combined_val = combined_val.map(add_token_counts, num_proc=2)
test_sells = test_sells.map(add_token_counts, num_proc=2)
test_medlane = test_medlane.map(add_token_counts, num_proc=2)
test_cochrane = test_cochrane.map(add_token_counts, num_proc=2)
test_plaba = test_plaba.map(add_token_counts, num_proc=2)
print("n_tokens column added to all splits")

from collections import Counter

train_domain_counts = Counter(mixed_train["dataset"])
val_domain_counts = Counter(combined_val["dataset"])

print(f"{'Split':<14} {'Total':>8} {'SELLS':>8} {'MedLane':>8} {'Cochrane':>8} {'PLABA':>8}")
print("-" * 62)
print(f"{'train':<14} {len(mixed_train):>8} {train_domain_counts.get('sells',0):>8} "
      f"{train_domain_counts.get('medlane',0):>8} {train_domain_counts.get('cochrane',0):>8} "
      f"{train_domain_counts.get('plaba',0):>8}")
print(f"{'val':<14} {len(combined_val):>8} {val_domain_counts.get('sells',0):>8} "
      f"{val_domain_counts.get('medlane',0):>8} {val_domain_counts.get('cochrane',0):>8} "
      f"{val_domain_counts.get('plaba',0):>8}")
print(f"{'test_sells':<14} {len(test_sells):>8}")
print(f"{'test_medlane':<14} {len(test_medlane):>8}")
print(f"{'test_cochrane':<14} {len(test_cochrane):>8}")
print(f"{'test_plaba':<14} {len(test_plaba):>8}")

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

datasets_order = ["sells", "medlane", "cochrane"]
colors = {"sells": "#4C72B0", "medlane": "#DD8452", "cochrane": "#55A868", "plaba": "#C44E52"}

train_counts = [train_domain_counts.get(d, 0) for d in datasets_order]
val_counts = [val_domain_counts.get(d, 0) for d in datasets_order]
train_colors = [colors[d] for d in datasets_order]

axes[0].bar(datasets_order, train_counts, color=train_colors, edgecolor="black", linewidth=0.4)
axes[0].set_title("Train — Examples per Dataset (after T=2 mixing)")
axes[0].set_ylabel("count")
for i, c in enumerate(train_counts):
    axes[0].text(i, c + max(train_counts)*0.01, f"{c:,}", ha="center", fontsize=8)

axes[1].bar(datasets_order, val_counts, color=train_colors, edgecolor="black", linewidth=0.4)
axes[1].set_title("Val — Examples per Dataset")
axes[1].set_ylabel("count")
for i, c in enumerate(val_counts):
    axes[1].text(i, c + max(val_counts)*0.01, f"{c:,}", ha="center", fontsize=8)

for ax in axes:
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{int(x):,}"))

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_dataset_composition.png", dpi=150, bbox_inches="tight")
plt.show()

train_lens = mixed_train["n_tokens"]
val_lens = combined_val["n_tokens"]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, lens, title, color in [
    (axes[0], train_lens, "Train", "steelblue"),
    (axes[1], val_lens, "Val", "coral"),
]:
    ax.hist(lens, bins=120, color=color, edgecolor="black", linewidth=0.2, alpha=0.85)
    ax.set_title(f"{title} — Token Length Distribution (n={len(lens):,})")
    ax.set_xlabel("tokens (pre-template)")
    ax.set_ylabel("count")

    cutoffs = [256, 512, 768, 1024, 1536]
    for c in cutoffs:
        ax.axvline(c, color="red", linestyle="--", alpha=0.5, linewidth=0.7)
        kept_pct = sum(1 for l in lens if l <= c) / len(lens) * 100
        y_pos = ax.get_ylim()[1] * 0.92
        ax.text(c + 8, y_pos, f"{c}\n({kept_pct:.1f}%)", fontsize=6.5, color="red")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_token_length_dist.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"\n{'cutoff':>8} {'train_kept':>12} {'train_%':>9} {'val_kept':>10} {'val_%':>9}")
print("-" * 52)
for c in [256, 512, 768, 1024, 1536, 2048]:
    tk = sum(1 for l in train_lens if l <= c)
    vk = sum(1 for l in val_lens if l <= c)
    print(f"{c:>8} {tk:>12,} {tk/len(train_lens)*100:>8.1f}% {vk:>10,} {vk/len(val_lens)*100:>8.1f}%")

print(f"\ntrain — min: {min(train_lens)}, max: {max(train_lens)}, "
      f"median: {int(np.median(train_lens))}, mean: {np.mean(train_lens):.0f}, "
      f"p95: {int(np.percentile(train_lens, 95))}, p99: {int(np.percentile(train_lens, 99))}")
print(f"val   — min: {min(val_lens)}, max: {max(val_lens)}, "
      f"median: {int(np.median(val_lens))}, mean: {np.mean(val_lens):.0f}, "
      f"p95: {int(np.percentile(val_lens, 95))}, p99: {int(np.percentile(val_lens, 99))}")

domains = ["sells", "medlane", "cochrane"]

domain_lens = {}
for d in domains:
    subset = mixed_train.filter(lambda row: row["dataset"] == d)
    domain_lens[d] = subset["n_tokens"]

fig, ax = plt.subplots(figsize=(8, 5))

bp_data = [domain_lens[d] for d in domains]
bp = ax.boxplot(bp_data, labels=[d.upper() for d in domains], patch_artist=True,
                showfliers=True, flierprops=dict(marker=".", markersize=1, alpha=0.3))

for patch, d in zip(bp["boxes"], domains):
    patch.set_facecolor(colors[d])
    patch.set_alpha(0.7)

ax.axhline(512, color="red", linestyle="--", linewidth=0.7, label="512 cutoff")
ax.axhline(1024, color="darkred", linestyle="--", linewidth=0.7, label="1024 cutoff")
ax.legend(fontsize=8)
ax.set_ylabel("tokens")
ax.set_title("Token Length by Domain — Train Split")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_token_length_by_domain.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"\n{'domain':<12} {'median':>8} {'mean':>8} {'p95':>8} {'p99':>8} {'max':>8} "
      f"{'<512':>8} {'<1024':>8} {'>1024':>8}")
print("-" * 90)
for d in domains:
    ls = domain_lens[d]
    n = len(ls)
    print(f"{d:<12} {int(np.median(ls)):>8} {np.mean(ls):>8.0f} "
          f"{int(np.percentile(ls, 95)):>8} {int(np.percentile(ls, 99)):>8} {max(ls):>8} "
          f"{sum(1 for l in ls if l <= 512):>7}  {sum(1 for l in ls if l <= 1024):>7}  "
          f"{sum(1 for l in ls if l > 1024):>7}")

def word_count(text):
    return len(text.split())

domains_all = ["sells", "medlane", "cochrane", "plaba"]

all_test = {
    "sells": test_sells, "medlane": test_medlane,
    "cochrane": test_cochrane, "plaba": test_plaba,
}

fig, axes = plt.subplots(2, 2, figsize=(13, 10))
axes = axes.flatten()

for idx, d in enumerate(domains_all):
    ds = all_test[d]
    src_wc = [word_count(s) for s in ds["source"]]
    tgt_wc = [word_count(t) for t in ds["target"]]
    ax = axes[idx]

    ax.hist(src_wc, bins=60, alpha=0.6, color="indianred", label="source", edgecolor="black", linewidth=0.2)
    ax.hist(tgt_wc, bins=60, alpha=0.6, color="mediumseagreen", label="target", edgecolor="black", linewidth=0.2)
    ax.set_title(f"{d.upper()} test — Word Count (n={len(ds)})")
    ax.set_xlabel("words")
    ax.set_ylabel("count")
    ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_src_vs_tgt_wordcount.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"\n{'dataset':<12} {'src_med':>8} {'tgt_med':>8} {'ratio':>8} {'src_mean':>9} {'tgt_mean':>9}")
print("-" * 52)
for d in domains_all:
    ds = all_test[d]
    sw = [word_count(s) for s in ds["source"]]
    tw = [word_count(t) for t in ds["target"]]
    ratio = np.median(tw) / np.median(sw) if np.median(sw) > 0 else 0
    print(f"{d:<12} {int(np.median(sw)):>8} {int(np.median(tw)):>8} {ratio:>8.2f} "
          f"{np.mean(sw):>9.1f} {np.mean(tw):>9.1f}")

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()

for idx, d in enumerate(domains_all):
    ds = all_test[d]
    sw = np.array([word_count(s) for s in ds["source"]])
    tw = np.array([word_count(t) for t in ds["target"]])
    ax = axes[idx]

    ax.scatter(sw, tw, alpha=0.25, s=8, color=colors[d])
    lim = max(sw.max(), tw.max()) * 1.05
    ax.plot([0, lim], [0, lim], color="black", linewidth=0.7, linestyle="--", label="y=x (no change)")
    ax.set_xlim(0, lim)
    ax.set_ylim(0, lim)
    ax.set_xlabel("source words")
    ax.set_ylabel("target words")
    ax.set_title(f"{d.upper()} — Compression Scatter (n={len(ds)})")
    ax.legend(fontsize=7)

    longer = sum(1 for s, t in zip(sw, tw) if t > s)
    ax.text(0.95, 0.05, f"{longer}/{len(ds)} targets longer than source",
            transform=ax.transAxes, fontsize=7, ha="right", color="red")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_compression_scatter.png", dpi=150, bbox_inches="tight")
plt.show()

def readability_batch(texts):
    fre_vals = []
    fkg_vals = []
    for t in texts:
        t = t.strip()
        if len(t) == 0:
            continue
        fre_vals.append(textstat.flesch_reading_ease(t))
        fkg_vals.append(textstat.flesch_kincaid_grade(t))
    return np.array(fre_vals), np.array(fkg_vals)

readability_data = {}

for d in domains_all:
    ds = all_test[d]
    src_fre, src_fkg = readability_batch(ds["source"])
    tgt_fre, tgt_fkg = readability_batch(ds["target"])
    readability_data[d] = {
        "src_fre": src_fre, "src_fkg": src_fkg,
        "tgt_fre": tgt_fre, "tgt_fkg": tgt_fkg,
    }

print(f"{'dataset':<12} {'src_FRE':>9} {'tgt_FRE':>9} {'delta_FRE':>10} "
      f"{'src_FKG':>9} {'tgt_FKG':>9} {'delta_FKG':>10}")
print("-" * 72)
for d in domains_all:
    rd = readability_data[d]
    sf = rd["src_fre"].mean()
    tf = rd["tgt_fre"].mean()
    sk = rd["src_fkg"].mean()
    tk = rd["tgt_fkg"].mean()
    print(f"{d:<12} {sf:>9.2f} {tf:>9.2f} {tf - sf:>+10.2f} "
          f"{sk:>9.2f} {tk:>9.2f} {tk - sk:>+10.2f}")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for idx, d in enumerate(domains_all):
    rd = readability_data[d]
    ax = axes[idx // 2][idx % 2]

    ax.hist(rd["src_fre"], bins=50, alpha=0.55, color="indianred",
            label=f"source (mean={rd['src_fre'].mean():.1f})", edgecolor="black", linewidth=0.2)
    ax.hist(rd["tgt_fre"], bins=50, alpha=0.55, color="mediumseagreen",
            label=f"target (mean={rd['tgt_fre'].mean():.1f})", edgecolor="black", linewidth=0.2)
    ax.set_title(f"{d.upper()} — Flesch Reading Ease")
    ax.set_xlabel("FRE score (higher = easier)")
    ax.set_ylabel("count")
    ax.legend(fontsize=7)

plt.suptitle("Baseline Readability: Source vs Reference Target", fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_readability_fre.png", dpi=150, bbox_inches="tight")
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for idx, d in enumerate(domains_all):
    rd = readability_data[d]
    ax = axes[idx // 2][idx % 2]

    ax.hist(rd["src_fkg"], bins=50, alpha=0.55, color="indianred",
            label=f"source (mean={rd['src_fkg'].mean():.1f})", edgecolor="black", linewidth=0.2)
    ax.hist(rd["tgt_fkg"], bins=50, alpha=0.55, color="mediumseagreen",
            label=f"target (mean={rd['tgt_fkg'].mean():.1f})", edgecolor="black", linewidth=0.2)
    ax.set_title(f"{d.upper()} — Flesch-Kincaid Grade Level")
    ax.set_xlabel("grade level (lower = simpler)")
    ax.set_ylabel("count")
    ax.legend(fontsize=7)

plt.suptitle("Baseline Readability: Source vs Reference Target", fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_readability_fkg.png", dpi=150, bbox_inches="tight")
plt.show()

x = np.arange(len(domains_all))
width = 0.35

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

src_fre_means = [readability_data[d]["src_fre"].mean() for d in domains_all]
tgt_fre_means = [readability_data[d]["tgt_fre"].mean() for d in domains_all]
src_fkg_means = [readability_data[d]["src_fkg"].mean() for d in domains_all]
tgt_fkg_means = [readability_data[d]["tgt_fkg"].mean() for d in domains_all]

src_fre_std = [readability_data[d]["src_fre"].std() for d in domains_all]
tgt_fre_std = [readability_data[d]["tgt_fre"].std() for d in domains_all]
src_fkg_std = [readability_data[d]["src_fkg"].std() for d in domains_all]
tgt_fkg_std = [readability_data[d]["tgt_fkg"].std() for d in domains_all]

bars1 = axes[0].bar(x - width/2, src_fre_means, width, yerr=src_fre_std,
                     label="Source", color="indianred", edgecolor="black", linewidth=0.4, capsize=3)
bars2 = axes[0].bar(x + width/2, tgt_fre_means, width, yerr=tgt_fre_std,
                     label="Reference", color="mediumseagreen", edgecolor="black", linewidth=0.4, capsize=3)
axes[0].set_xticks(x)
axes[0].set_xticklabels([d.upper() for d in domains_all])
axes[0].set_ylabel("Flesch Reading Ease")
axes[0].set_title("Readability — Flesch RE (higher = easier)")
axes[0].legend(fontsize=8)

bars3 = axes[1].bar(x - width/2, src_fkg_means, width, yerr=src_fkg_std,
                     label="Source", color="indianred", edgecolor="black", linewidth=0.4, capsize=3)
bars4 = axes[1].bar(x + width/2, tgt_fkg_means, width, yerr=tgt_fkg_std,
                     label="Reference", color="mediumseagreen", edgecolor="black", linewidth=0.4, capsize=3)
axes[1].set_xticks(x)
axes[1].set_xticklabels([d.upper() for d in domains_all])
axes[1].set_ylabel("Flesch-Kincaid Grade Level")
axes[1].set_title("Readability — FK Grade (lower = simpler)")
axes[1].legend(fontsize=8)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_readability_bars.png", dpi=300, bbox_inches="tight")
plt.show()

import re

def sent_count(text):
    sents = re.split(r'(?<=[.!?])\s+', text.strip())
    return len([s for s in sents if len(s) > 0])

fig, axes = plt.subplots(2, 2, figsize=(13, 9))
axes = axes.flatten()

for idx, d in enumerate(domains_all):
    ds = all_test[d]
    src_sc = [sent_count(s) for s in ds["source"]]
    tgt_sc = [sent_count(t) for t in ds["target"]]
    ax = axes[idx]

    max_bin = max(max(src_sc), max(tgt_sc))
    bins = range(0, min(max_bin + 2, 30))
    ax.hist(src_sc, bins=bins, alpha=0.55, color="indianred",
            label=f"source (med={int(np.median(src_sc))})", edgecolor="black", linewidth=0.2)
    ax.hist(tgt_sc, bins=bins, alpha=0.55, color="mediumseagreen",
            label=f"target (med={int(np.median(tgt_sc))})", edgecolor="black", linewidth=0.2)
    ax.set_title(f"{d.upper()} — Sentence Count")
    ax.set_xlabel("sentences")
    ax.set_ylabel("count")
    ax.legend(fontsize=7)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_sentence_count.png", dpi=150, bbox_inches="tight")
plt.show()

def avg_word_len(text):
    words = text.split()
    if len(words) == 0:
        return 0
    return np.mean([len(w) for w in words])

fig, ax = plt.subplots(figsize=(10, 5))

src_awl = {d: [avg_word_len(s) for s in all_test[d]["source"]] for d in domains_all}
tgt_awl = {d: [avg_word_len(t) for t in all_test[d]["target"]] for d in domains_all}

x = np.arange(len(domains_all))
width = 0.35

ax.bar(x - width/2, [np.mean(src_awl[d]) for d in domains_all], width,
       label="Source", color="indianred", edgecolor="black", linewidth=0.4)
ax.bar(x + width/2, [np.mean(tgt_awl[d]) for d in domains_all], width,
       label="Reference", color="mediumseagreen", edgecolor="black", linewidth=0.4)

ax.set_xticks(x)
ax.set_xticklabels([d.upper() for d in domains_all])
ax.set_ylabel("avg characters per word")
ax.set_title("Average Word Length — Source vs Reference Target")
ax.legend()

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/Gatekeepn't/Data/fig_avg_word_length.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"\n{'dataset':<12} {'src_awl':>9} {'tgt_awl':>9} {'delta':>9}")
print("-" * 42)
for d in domains_all:
    s = np.mean(src_awl[d])
    t = np.mean(tgt_awl[d])
    print(f"{d:<12} {s:>9.2f} {t:>9.2f} {t - s:>+9.2f}")

import glob

saved = glob.glob("/content/drive/MyDrive/Gatekeepn't/Data/fig_*.png")
print(f"{len(saved)} figures saved:")
for f in sorted(saved):
    print(f"  {f}")