# -*- coding: utf-8 -*-
"""mimic-calibration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-tgEyQaBRvbQwonB00rnSLcjTe3-h2L
"""

!pip install -q transformers accelerate sentencepiece protobuf

import os, json, gc, time, random, torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import login
from google.colab import drive
import pandas as pd

drive.mount("/content/drive")

HF_TOKEN    = "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"
MIMIC_CSV   = "/content/drive/MyDrive/Gatekeepn't/Data/MIMIC-IV/mimic_calibration_40.csv"
RESULTS_DIR = "/content/drive/MyDrive/Gatekeepn't/results/human_eval/calibration_40v2"
os.makedirs(RESULTS_DIR, exist_ok=True)

login(token=HF_TOKEN)

SEED           = 42
MAX_NEW_TOKENS = 1024

df      = pd.read_csv(MIMIC_CSV)
sources = df["source"].tolist()
print(f"Loaded {len(sources)} calibration examples")
for i, s in enumerate(sources):
    print(f"\n--- Example {i+1} ---\n{s}\n")

def run_inference(model, tok, sources, save_path):
    preds = []
    tok.padding_side = "left"

    for src in sources:
        instruction = (
            f"[REVIEW] Simplify the following medical text into plain "
            f"language that a patient without medical training can "
            f"understand:\n\n{src}"
        )
        prompt = tok.apply_chat_template(
            [{"role": "user", "content": instruction}],
            add_generation_prompt=True,
            tokenize=False,
        )
        encoded   = tok(prompt, return_tensors="pt").to(model.device)
        input_len = encoded["input_ids"].shape[1]

        with torch.no_grad():
            out = model.generate(
                **encoded,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=False,
                repetition_penalty=1.1,
                pad_token_id=tok.pad_token_id,
            )

        text = tok.decode(out[0][input_len:], skip_special_tokens=True).strip()
        if not text:
            text = "[EMPTY]"
        preds.append(text)
        print(f"  Done: {src[:60]}...")

    tok.padding_side = "right"
    with open(save_path, "w") as f:
        json.dump(preds, f)
    print(f"Saved to {save_path}")
    return preds

print("Loading zero-shot model...")
model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    torch_dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
    token=HF_TOKEN,
)
model.eval()
tok = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct", token=HF_TOKEN)
tok.pad_token = tok.eos_token

preds_exp1 = run_inference(model, tok, sources, f"{RESULTS_DIR}/exp1_preds.json")

del model, tok
gc.collect()
torch.cuda.empty_cache()
print("Cleared GPU")

model_path = "/content/drive/MyDrive/Gatekeepn't/models/exp2v2_sells_only/merged_bf16"
print(f"Loading {model_path}...")
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
)
model.eval()
tok = AutoTokenizer.from_pretrained(model_path)
tok.pad_token = tok.eos_token

preds_exp2 = run_inference(model, tok, sources, f"{RESULTS_DIR}/exp2_preds.json")

del model, tok
gc.collect()
torch.cuda.empty_cache()
print("Cleared GPU")

model_path = "/content/drive/MyDrive/Gatekeepn't/models/exp3a_mixed_1024/merged_bf16"
print(f"Loading {model_path}...")
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="sdpa",
)
model.eval()
tok = AutoTokenizer.from_pretrained(model_path)
tok.pad_token = tok.eos_token

preds_exp3 = run_inference(model, tok, sources, f"{RESULTS_DIR}/exp3_preds.json")

del model, tok
gc.collect()
torch.cuda.empty_cache()
print("Cleared GPU")

# Load preds in case of kernel restart
for tag, path in [("exp1", f"{RESULTS_DIR}/exp1_preds.json"),
                  ("exp2", f"{RESULTS_DIR}/exp2_preds.json"),
                  ("exp3", f"{RESULTS_DIR}/exp3_preds.json")]:
    with open(path) as f:
        locals()[f"preds_{tag}"] = json.load(f)

out_df = df.copy()
out_df["pred_exp1_zero_shot"]  = preds_exp1
out_df["pred_exp2_sells_only"] = preds_exp2
out_df["pred_exp3_mixed"]      = preds_exp3

# Blind: shuffle column order so annotators don't know which is which
pred_cols = ["pred_exp1_zero_shot", "pred_exp2_sells_only", "pred_exp3_mixed"]
shuffled  = pred_cols.copy()
random.seed(SEED)
random.shuffle(shuffled)

blind_map = {col: f"Simplification_{chr(65+i)}" for i, col in enumerate(shuffled)}
key_map   = {v: k.replace("pred_", "") for k, v in blind_map.items()}

blind_df = df[["source"]].copy()
for col in shuffled:
    blind_df[blind_map[col]] = out_df[col]

# Save
out_df.to_csv(f"{RESULTS_DIR}/calibration_raw.csv", index=False)
blind_df.to_csv(f"{RESULTS_DIR}/calibration_blind.csv", index=False)
with open(f"{RESULTS_DIR}/calibration_blind_key.json", "w") as f:
    json.dump(key_map, f, indent=2)

print(f"\nFiles saved to {RESULTS_DIR}/")
print(f"  calibration_blind.csv  — share this with annotators")
print(f"  calibration_raw.csv    — keep this")
print(f"  calibration_blind_key.json — do NOT share until after annotation")
print(f"\nBlind key (keep secret):")
for label, model_name in key_map.items():
    print(f"  {label} -> {model_name}")

print(f"\n--- Calibration blind CSV preview ---")
print(blind_df.to_string())